xp_config:
  model_type: Dual_Path_RNN
  dataset: ISSAI_KSC2
  use_tb_logger: false
  speaker_num: 2

data:
  mix_dir: ./mixed_data/
  ref_dirs: ./targets/
  train_split: 0.8
  val_split: 0.1
  num_workers: 1  
  batch_size: 1
  sample_rate: 16000
  chunk_size: 32000
  least_size: 16000
  seed: 42
  
model:
  in_channels: 256
  out_channels: 64 
  hidden_channels: 128
  kernel_size: 2
  rnn_type: LSTM
  norm: ln
  dropout: 0
  bidirectional: true
  num_layers: 6
  K: 250
  speaker_num: 2
trainer:
  num_epochs: 100
  device: 'cuda'
  best_weights: False
  checkpointing: false
  checkpoint_interval: 5
  model_name: VADNet
  path_to_weights: './weights'
  ckpt_folder: ./checkpoints/
  speaker_num: 2
  resume: false
training:
  optim: Adam   ### Adam, RMSprop, SGD
  lr: !!float 0.01
  weight_decay: 1.0e-05
  momentum: 0
  clip_norm: 5