xp_config:
  model_type: Dual_Path_RNN
  dataset: ISSAI_KSC2
  use_tb_logger: false
  speaker_num: 2

data:
  data_dir: F:/ISSAI_KSC2_unpacked/DIHARD_DATA_INFO/CONCATED_DFS_k_2.csv
  csv_file: True
  total_percent: 0.0005 
  train_percent: 0.8
  valid_percent: 0.1
  test_percent: 0.1
  num_workers: 6  
  batch_size: 1
  pin_memory: True
  seed: 42
  sample_rate: 16000
  chunk_size: 32000
  least_size: 16000
  
model:
  in_channels: 256
  out_channels: 64 
  hidden_channels: 128
  kernel_size: 2
  rnn_type: LSTM
  norm: ln
  dropout: 0
  bidirectional: true
  num_layers: 6
  K: 250
  speaker_num: 2
trainer:
  num_epochs: 100
  device: 'cuda'
  best_weights: False
  checkpointing: false
  checkpoint_interval: 5
  model_name: Dual_Path_RNN
  path_to_weights: './weights'
  ckpt_folder: ./checkpoints/
  speaker_num: 2
  resume: false
training:
  optim: Adam   ### Adam, RMSprop, SGD
  lr: !!float 0.01
  weight_decay: 1.0e-05
  momentum: 0
  clip_norm: 5