xp_config:
  model_type: Dual_Path_RNN
  dataset: ISSAI_KSC2
  use_tb_logger: false
  speaker_num: 2

data:
  data_root: 'F:/ISSAI_KSC2_unpacked/DIHARD_DATA_INFO/CONCATED_DFS_tts=2000_k_2.csv'
  total_percent: 1.0
  train_percent: 0.8
  valid_percent: 0.2
  test_percent: 0.0
  shuffle: true
  num_workers: 0 
  batch_size: 3
  pin_memory: True
  sample_rate: 16000
  chunk_size: 32000
  least_size: 16000
  seed: 42

model:
  in_channels: 256
  out_channels: 64 
  hidden_channels: 128
  kernel_size: 2
  rnn_type: LSTM
  norm: ln
  dropout: 0
  bidirectional: true
  num_layers: 6
  K: 250
  speaker_num: 2
trainer:
  num_epochs: 100
  device: 'cuda'
  best_weights: True
  checkpointing: True
  checkpoint_interval: 3
  model_name: Dual_Path_RNN
  trained_model: '' # weights/Dual_Path_RNN_1_-0.1336.pt 
  path_to_weights: './weights'
  ckpt_folder: ./checkpoints/
  speaker_num: 2
  resume: false
training:
  optim: Adam   ### Adam, RMSprop, SGD
  lr: !!float 0.0003
  weight_decay: 1.0e-05
  momentum: 0
  clip_norm: 5