xp_config:
  model_type: Dual_Path_RNN
  dataset: ISSAI_KSC2
  use_tb_logger: false
  speaker_num: 2

data:
  data_root: 'F:/ISSAI_KSC2_unpacked/DIHARD_DATA_INFO/CONCATED_DFS_tts=2000_k_2.csv'
  train_percent: 0.8
  valid_percent: 0.2
  test_percent: 0.0
  shuffle: true
  num_workers: 0 
  batch_size: 1
  pin_memory: True
  sample_rate: 16000
  chunk_size: 32000
  least_size: 16000
  seed: 42

datasets:
  train_dataroot_mix: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/tr_mix.scp
  train_dataroot_target_s1: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/tr_s1.scp 
  train_dataroot_target_s2: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/tr_s2.scp
  val_dataroot_mix: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/cv_mix.scp
  val_dataroot_target_s1: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/cv_s1.scp 
  val_dataroot_target_s2: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/cv_s2.scp
  shuffle: true
  num_workers: 0 
  batch_size: 1
  pin_memory: True
  sample_rate: 16000
  chunk_size: 32000
  least_size: 16000
  seed: 42

model:
  in_channels: 256
  out_channels: 64 
  hidden_channels: 128
  kernel_size: 2
  rnn_type: LSTM
  norm: ln
  dropout: 0
  bidirectional: true
  num_layers: 6
  K: 250
  speaker_num: 2
trainer:
  num_epochs: 100
  device: 'cuda'
  best_weights: False
  checkpointing: false
  checkpoint_interval: 5
  model_name: Dual_Path_RNN
  path_to_weights: './weights'
  ckpt_folder: ./checkpoints/
  speaker_num: 2
  resume: false
training:
  optim: Adam   ### Adam, RMSprop, SGD
  lr: !!float 0.01
  weight_decay: 1.0e-05
  momentum: 0
  clip_norm: 5